---
name: 'python-safety'
description: 'python-safety by Pipeline Components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  options:
    description: 'optional arguments'
    required: false
    default: ''
  action:
    description: 'Action'
    required: true
    default: 'check'
runs:
  using: 'docker'
  image: docker://pipelinecomponents/python-safety
  args:
    - safety
    - '${{ inputs.action }}'
    - '${{ inputs.options }}'
